### ISSUE TITLE
[question] does it matter on windows msys2 python3 / Gtk3 ?

### ISSUE THREAD

**Issue by elelay** [quodlibet/senf#10]
I'm porting gPodder (python3, Gtk3, using Gtk.Builder) to windows, adapting your great installer scripts for QuodLibet (WIP is at [gPodder #453](https://github.com/gpodder/gpodder/pull/453).

Things seem to work nicely with native `str` type so I'm curious: do you know what operations will fail if I keep it like that and don't use `fsnative`?

I maybe have an issue with path encoding: I have to use ctypes to call `bindtextdomain` for Gtk to pick the locale:
```
    gpodder_script = sys.argv[0]
    gpodder_script = os.path.realpath(gpodder_script)
    gpodder_dir = os.path.join(os.path.dirname(gpodder_script), '..')
    prefix = os.path.abspath(os.path.normpath(gpodder_dir))
    locale_dir = os.path.join(prefix, 'share', 'locale')

    from ctypes import cdll
    libintl = cdll.LoadLibrary('libintl-8.dll')
    libintl.bindtextdomain(domain.encode('mbcs'), localedir.encode('mbcs'))
```
I do have to provide bytes to the call to `libintl.bindtextdomain`, so I have to encode the path to something. `mbcs` seems to be recommended in [sys.getfilesystemencoding()](https://docs.python.org/3/library/sys.html#sys.getfilesystemencoding). Would it be better to use **senf.fsn2bytes**?

**Comment by lazka** [comment]
> Things seem to work nicely with native str type so I'm curious: do you know what operations will fail if I keep it like that and don't use fsnative?

str works fine for Python 3. In QL I wanted to support Py2/3 at the same time until things were stable enough, which resulted in this lib.

> I do have to provide bytes to the call to libintl.bindtextdomain, so I have to encode the path to something.

If you use "gettext.bindtextdomain" before importing Gtk, things should work as well.

> mbcs seems to be recommended in sys.getfilesystemencoding(). Would it be better to use senf.fsn2bytes?

In newer Python sys.getfilesystemencoding() returns "utf-8" on Windows. It depends on which Windows API the C code of bindtextdomain uses. I'd guess it doesn't support Unicode, so "mbcs" would be right here. But keep in mind that encoding to mbcs can fail for unicode paths.

**Comment by elelay** [comment]
Thanks for your answer! This diverges a bit from senf, but I've continued experimenting...

I already call `gettext.bindtextdomain` before importing `gi` and loading `Gtk` from repository, but it is not enough on windows. I need to do the `libintl.bindtextdomain` call or I don't get translated labels in my UI (I use `Gtk.Builder`, not building the UI in python code like you do in QuodLibet).

`libintl.bindtextdomain` is indeed not Unicode aware (according to a [glib2 comment](https://gitlab.gnome.org/GNOME/glib/blob/master/glib/ggettext.c#L52)).

I've tried installing the portable version of gpodder to `C:\éric`: no problem with **mbcs**: I get a localized UI. It doesn't work with **utf-8**. So the path given to `libintl.bindtextdomain` must be encoded in **mbcs**.

I've tried installing the portable version of gpodder or quodlibet to `C:\太医谈字`: python doesn't start:
```
C:\Users\IEUser>C:\太医谈字\quodlibet-4.0.2-portable\data\bin\python3.6.exe
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000acc (most recent call first):

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
I also tried to install it in `C:\σ`: same error. This is in a virtualbox VM from modern.ie [MSEdge on Win10 (x64) Stable (17.17134)](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

Just for the fun, since gPodder won't start in the first place, I tried starting gPodder from an ascii directory (`C:\gpodder`) and calling `libintl.bindtextdomain` with a different path: `'C:\\σ\\gpodder-3.10.1-portable\\data\\share\\locale'` or `'C:\太医谈字\gpodder-3.10.1-portable\\data\\share\\locale'`. They can't be encoded in **mbcs** so it doesn't work. It might work if windows was installed with a different code page.

I tried using [GetShortPathName](https://stackoverflow.com/questions/23598289/how-to-get-windows-short-file-name-in-python), but it doesn't transform `'C:\\σ'` so it won't help:
```
>>> _ = _GetShortPathNameW('c:\σ', output_buf, output_buf_size)
>>> output_buf.value
'c:\\σ'
>>> _ = _GetShortPathNameW('c:\太医谈字', output_buf, output_buf_size)
>>> output_buf.value
'c:\\DC34~1'
```
My conclusion is that `Gtk.Builder` localization is broken on windows (msys2) when installation path contains characters not mappable to the system's codepage. What do you think?

**Comment by lazka** [comment]
I've never used Gtk.Builder, so that might be.

I'll look into the Python error some time. I know I had that working some years ago, but it might have regressed :/

For the translation path, you might get away with passing a relative path (which you control).

**Comment by elelay** [comment]
OK, thanks.
