### ISSUE TITLE
1.4.1: test_getuserdir and test_expanduser_user fail during packaging

### ISSUE THREAD

**Issue by dvzrv** [quodlibet/senf#12]
Hi! I'm packaging python-senf for Arch Linux.

When building and testing 1.4.1 I ran into the following issues with the tests:

```
=================================== FAILURES ===================================
_______________________________ test_getuserdir ________________________________

    def test_getuserdir():
        # type: () -> None

        userdir = _get_userdir()
        assert isinstance(userdir, fsnative)

        with pytest.raises(TypeError):
            _get_userdir(notfsnative(u"foo"))

        if sys.platform == "win32":
            otherdir = _get_userdir(u"foo")
            assert otherdir == os.path.join(os.path.dirname(userdir), u"foo")
        else:
            user = os.path.basename(userdir)
>           assert _get_userdir() == _get_userdir(user)
E           AssertionError: assert '/build' == None
E             -'/build'
E             +None

tests/test_api.py:194: AssertionError
_____________________________ test_expanduser_user _____________________________

    def test_expanduser_user():
        # type: () -> None

        home = _get_userdir()
        user = os.path.basename(home)

>       assert expanduser("~" + user) == home
E       AssertionError: assert '~build' == '/build'
E         - ~build
E         ? ^
E         + /build
E         ? ^

tests/test_api.py:244: AssertionError
=================== 2 failed, 53 passed, 9 skipped in 9.56s ====================
```

Packages are being built in a pristine container, that only gets installed, what the package requires.
The build user home gets reset for each package and the user running the build is called `builduser`, with its `HOME` at `/build` within that container.
Somehow the assumptions in those tests don't seem to be able to cover this use-case (yet).

**Comment by lazka** [comment]
> Hi! I'm packaging python-senf for Arch Linux.

hey, thanks. What's the reason for packaging this in Arch if I may ask? This package was mostly useful for transitioning things from py2 to py3 and never really got any users besides my own packages, so I'm curious.

**Comment by dvzrv** [comment]
Judging from [quodlibet's pythonproject.toml](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/pyproject.toml#L22) I assumed, that it is a necessary dependency for quodlibet (which I also package).

**Comment by lazka** [comment]
> Judging from [quodlibet's pythonproject.toml](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/pyproject.toml#L22) I assumed, that it is a necessary dependency for quodlibet (which I also package).

Oh, that shouldn't have ended up there, sorry. senf is vendored in quodlibet itself: https://github.com/quodlibet/quodlibet/tree/master/quodlibet/quodlibet/packages

> (which I also package).

thanks!

**Comment by lazka** [comment]
I've also removed the dependency from the quodlibet pyproject.toml file.

Thanks for the report.
